language:
  - php
  - node_js
sudo: required
dist: trusty
php:
  - '7.0'
node_js:
  - 'node'
env:
  global:
    - MIN_PHP_VERSION="7.0"
before_script:
  - phpenv config-rm xdebug.ini
  - npm install
script: npm test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4598aef0172b069a6ad3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
