language: php
# sudo: required
dist: xenial
php:
  - '7.0'
env: MIN_PHP_VERSION="7.0"
before_install:
  - phpenv config-rm xdebug.ini
  - npm install 3.10.10
before_script:
  - npm install
script: npm test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4598aef0172b069a6ad3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
